# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

# Coverage configuration
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%

    patch:
      default:
        target: 80%

# Ignore patterns
ignore:
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/jest.config.ts"
  - "**/jest.preset.js"
  - "**/__mocks__/**"
  - ".nx/**"
  - "dist/**"
  - "coverage/**"
  - "nx-astro-e2e/**"

# Comment configuration
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
